export interface SteamLanguage {
  code: string;
  label: string;
}

export const STEAM_LANGUAGES: SteamLanguage[] = [
  { code: 'afrikaans', label: 'Afrikaans' },
  { code: 'albanian', label: 'Albanian' },
  { code: 'amharic', label: 'Amharic' },
  { code: 'arabic', label: 'Arabic' },
  { code: 'armenian', label: 'Armenian' },
  { code: 'assamese', label: 'Assamese' },
  { code: 'azerbaijani', label: 'Azerbaijani' },
  { code: 'bangla', label: 'Bangla' },
  { code: 'basque', label: 'Basque' },
  { code: 'belarusian', label: 'Belarusian' },
  { code: 'bosnian', label: 'Bosnian' },
  { code: 'bulgarian', label: 'Bulgarian' },
  { code: 'catalan', label: 'Catalan' },
  { code: 'cherokee', label: 'Cherokee' },
  { code: 'croatian', label: 'Croatian' },
  { code: 'czech', label: 'Czech' },
  { code: 'danish', label: 'Danish' },
  { code: 'dari', label: 'Dari' },
  { code: 'dutch', label: 'Dutch' },
  { code: 'english', label: 'English' },
  { code: 'estonian', label: 'Estonian' },
  { code: 'filipino', label: 'Filipino' },
  { code: 'finnish', label: 'Finnish' },
  { code: 'french', label: 'French' },
  { code: 'galician', label: 'Galician' },
  { code: 'georgian', label: 'Georgian' },
  { code: 'german', label: 'German' },
  { code: 'greek', label: 'Greek' },
  { code: 'gujarati', label: 'Gujarati' },
  { code: 'hausa', label: 'Hausa' },
  { code: 'hebrew', label: 'Hebrew' },
  { code: 'hindi', label: 'Hindi' },
  { code: 'hungarian', label: 'Hungarian' },
  { code: 'icelandic', label: 'Icelandic' },
  { code: 'igbo', label: 'Igbo' },
  { code: 'indonesian', label: 'Indonesian' },
  { code: 'irish', label: 'Irish' },
  { code: 'italian', label: 'Italian' },
  { code: 'japanese', label: 'Japanese' },
  { code: 'kiche', label: "K'iche'" },
  { code: 'kannada', label: 'Kannada' },
  { code: 'kazakh', label: 'Kazakh' },
  { code: 'khmer', label: 'Khmer' },
  { code: 'kinyarwanda', label: 'Kinyarwanda' },
  { code: 'konkani', label: 'Konkani' },
  { code: 'korean', label: 'Korean' },
  { code: 'kyrgyz', label: 'Kyrgyz' },
  { code: 'latvian', label: 'Latvian' },
  { code: 'lithuanian', label: 'Lithuanian' },
  { code: 'luxembourgish', label: 'Luxembourgish' },
  { code: 'macedonian', label: 'Macedonian' },
  { code: 'malay', label: 'Malay' },
  { code: 'malayalam', label: 'Malayalam' },
  { code: 'maltese', label: 'Maltese' },
  { code: 'maori', label: 'Maori' },
  { code: 'marathi', label: 'Marathi' },
  { code: 'mongolian', label: 'Mongolian' },
  { code: 'nepali', label: 'Nepali' },
  { code: 'norwegian', label: 'Norwegian' },
  { code: 'odia', label: 'Odia' },
  { code: 'persian', label: 'Persian' },
  { code: 'polish', label: 'Polish' },
  { code: 'portuguese_brazil', label: 'Portuguese - Brazil' },
  { code: 'portuguese', label: 'Portuguese - Portugal' },
  { code: 'punjabi', label: 'Punjabi (Gurmukhi)' },
  { code: 'punjabi_shahmukhi', label: 'Punjabi (Shahmukhi)' },
  { code: 'quechua', label: 'Quechua' },
  { code: 'romanian', label: 'Romanian' },
  { code: 'russian', label: 'Russian' },
  { code: 'scots', label: 'Scots' },
  { code: 'serbian', label: 'Serbian' },
  { code: 'schinese', label: 'Simplified Chinese' },
  { code: 'sindhi', label: 'Sindhi' },
  { code: 'sinhala', label: 'Sinhala' },
  { code: 'slovak', label: 'Slovak' },
  { code: 'slovenian', label: 'Slovenian' },
  { code: 'sorani', label: 'Sorani' },
  { code: 'sotho', label: 'Sotho' },
  { code: 'latam', label: 'Spanish - Latin America' },
  { code: 'spanish', label: 'Spanish - Spain' },
  { code: 'swahili', label: 'Swahili' },
  { code: 'swedish', label: 'Swedish' },
  { code: 'tajik', label: 'Tajik' },
  { code: 'tamil', label: 'Tamil' },
  { code: 'tatar', label: 'Tatar' },
  { code: 'telugu', label: 'Telugu' },
  { code: 'thai', label: 'Thai' },
  { code: 'tigrinya', label: 'Tigrinya' },
  { code: 'tchinese', label: 'Traditional Chinese' },
  { code: 'tswana', label: 'Tswana' },
  { code: 'turkish', label: 'Turkish' },
  { code: 'turkmen', label: 'Turkmen' },
  { code: 'ukrainian', label: 'Ukrainian' },
  { code: 'urdu', label: 'Urdu' },
  { code: 'uyghur', label: 'Uyghur' },
  { code: 'uzbek', label: 'Uzbek' },
  { code: 'valencian', label: 'Valencian' },
  { code: 'vietnamese', label: 'Vietnamese' },
  { code: 'welsh', label: 'Welsh' },
  { code: 'wolof', label: 'Wolof' },
  { code: 'xhosa', label: 'Xhosa' },
  { code: 'yoruba', label: 'Yoruba' },
  { code: 'zulu', label: 'Zulu' },
];

export function searchLanguages(query: string): SteamLanguage[] {
  const q = query.toLowerCase().trim();
  if (!q) return STEAM_LANGUAGES;
  return STEAM_LANGUAGES.filter(l => l.label.toLowerCase().includes(q));
}
